title: "HINF 5016: Natural Language Processing in Health"
description: "Jan. 3, 2022 - April 8, 2022, 5:00-8:00 pm East Time on Wednesdays | 
              1300 York Ave. (C-200)"
theme: jekyll-theme-cayman
